# Generated by Django 4.1.5 on 2023-02-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=200)),
                ('Fess', models.FloatField()),
                ('Duration', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
